import {
  EXPO_FIREBASE_API_KEY,
  EXPO_FIREBASE_AUTH_DOMAIN,
  EXPO_FIREBASE_PROJECT_ID,
  EXPO_FIREBASE_STORAGE_BUCKET,
  EXPO_FIREBASE_MESSAGING_SENDER_ID,
  EXPO_FIREBASE_APP_ID,
  EXPO_FIREBASE_MEASUREMENT_ID,
} from "@env";

export const FIREBASE_API_KEY = EXPO_FIREBASE_API_KEY;
export const FIREBASE_AUTH_DOMAIN = EXPO_FIREBASE_AUTH_DOMAIN;
export const FIREBASE_PROJECT_ID = EXPO_FIREBASE_PROJECT_ID;
export const FIREBASE_STORAGE_BUCKET = EXPO_FIREBASE_STORAGE_BUCKET;
export const FIREBASE_MESSAGING_SENDER_ID = EXPO_FIREBASE_MESSAGING_SENDER_ID;
export const FIREBASE_APP_ID = EXPO_FIREBASE_APP_ID;
export const FIREBASE_MEASUREMENT_ID = EXPO_FIREBASE_MEASUREMENT_ID;
